<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate Account' => '',
    'Administration' => '',
    'Administrator' => '',
    'Administrator Auth Logs' => '',
    'Administrators' => '',
    'Application Configuration' => '',
    'Are you sure you want to activate this account?' => '',
    'Are you sure you want to restore default values?' => '',
    'Are you sure you want to suspend this account?' => '',
    'Auth Logs' => '',
    'Cache has been flushed.' => '',
    'Configuration updated.' => '',
    'Create' => '',
    'Create Admin' => '',
    'Default values restored.' => '',
    'Follow the link below to access {appName} administration panel:' => '',
    'Login' => '',
    'Logout' => '',
    'Logs' => '',
    'Maintenance' => '',
    'Please contact to another {appName} administrator for account reactivation.' => '',
    'Profile' => '',
    'Restore defaults' => '',
    'Save' => '',
    'Settings' => '',
    'Suspend Account' => '',
    'Update' => '',
    'Update Admin: ' => '',
    'Update User: ' => '',
    'User Auth Logs' => '',
    'Users' => '',
    'Your account credentials:' => '',
    'Your administration account at {appName}' => '',
    'Your administration account at {appName} has been created' => '',
    'Your administration account at {appName} has been suspended' => '',
    '{appName} Administration' => '',
];
