<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear application runtime cache, making sure recent changes appear.' => '',
    'Flush Cache' => '',
    'Generate Sitemap' => '',
    'Generates sitemap (regenerates if exists), applying recent changes to it.' => '',
    'Maintenance: flush cache, etc.' => '',
    'Manage administrator accounts' => '',
    'Manage users accounts' => '',
    'Note: some actions may take long time to be performed.' => '',
    'Setup application name, email etc.' => '',
    'Sitemap generation started. It may take some time to be complete.' => '',
    'This section allows you to perform some maintenance of your system.' => '',
];
