<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cookie Based' => '',
    'Duration' => '',
    'Incorrect password.' => '',
    'Incorrect username or password.' => '',
    'Last Login Date' => '',
    'Log in {appName}' => '',
    'Login' => '',
    'Old Password' => '',
    'Password' => '',
    'Password reset token cannot be blank.' => '',
    'Please choose your new password:' => '',
    'Please contact {appName} administrator for account reactivation:' => '',
    'Please fill out the following fields to login:' => '',
    'Please fill out the following fields to signup:' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Remember Me' => '',
    'Repeat Password' => '',
    'Request password reset' => '',
    'Reset Password' => '',
    'Reset password' => '',
    'Sign up with {appName}' => '',
    'Signup' => '',
    'This account is inactive.' => '',
    'UserAgent' => '',
    'Username' => '',
    'Wrong password reset token.' => '',
    'Your account at {appName} has been suspended' => '',
    'Your account credentials:' => '',
    '{appName} - Request password reset' => '',
    '{appName} - Reset password' => '',
];
